# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        shell: powershell
        run: |
          pip install sphinx
          pip install solar-theme
          .\docs\make.bat html
      - name: Publish
        if: github.ref == 'refs/heads/master'
        shell: powershell
        run: |
          git clone --single-branch --branch master https://$API_TOKEN_GITHUB@github.com/fabienfl-orc/dfir-orc.github.io.git
          Copy-Item -Force -Recurse .\docs\build\html\* dfir-orc.github.io/
          cd dfir-orc.github.io/
          git add --all
          git status
          git -c "user.name=fabienfl" -c "user.email=fabien.fl-orc@ssi.gouv.fr" commit -m "Update by GitHub Action"          
          git push
