name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: pwsh
        run: |
          pip install sphinx
          pip install solar-theme
          .\docs\make.bat html
      - name: Publish
        if: github.ref == 'refs/heads/master'
        shell: pwsh
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git clone --single-branch --branch master "https://$ENV:API_TOKEN_GITHUB@github.com/fabienfl-orc/dfir-orc.github.io.git"
          Copy-Item -Force -Recurse .\docs\build\html\* dfir-orc.github.io/
          cd dfir-orc.github.io/
          git add --all
          git status
          git -c "user.name=fabienfl" -c "user.email=fabien.fl-orc@ssi.gouv.fr" commit -m "Update by GitHub Action"          
          git push
