# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          pip install sphinx
          pip install solar-theme
          cd docs
          .\make.bat html
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: cpina/github-action-push-to-another-repository@v1.1
        with:
          # Source directory from the origin directory
          source-directory: docs/build
          # Name of the destination username/organization
          destination-github-username: fabienfl-orc
          # Destination repository
          destination-repository-name: dfir-orc.github.io.git
          # Email for the git commit
          user-email: fabien.fl-orc@ssi.gouv.fr
